# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/bionic64"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 18080
    vagrant1.vm.network "forwarded_port", guest: 443, host: 18443
    vagrant1.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
    end
  end

  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/bionic64"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 18081
    vagrant2.vm.network "forwarded_port", guest: 443, host: 18444
    vagrant2.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
    end
  end

  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu/bionic64"
    vagrant3.vm.network "forwarded_port", guest: 80, host: 18082
    vagrant3.vm.network "forwarded_port", guest: 443, host: 18445
    vagrant3.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
    end
  end

end
