server:
  port: 8091

kafka:
  server:
    address: "localhost:9092"

spring:
  flyway:
    enabled: false
  datasource:
    hikari:
      mysql1:
        jdbc-url: "jdbc:mysql://localhost:11001/test"
        username: "root"
        password: "P@ssw0rd"
        driver-class-name: com.mysql.cj.jdbc.Driver
      mysql2:
        jdbc-url: "jdbc:mysql://localhost:11002/test"
        username: "root"
        password: "P@ssw0rd"
        driver-class-name: com.mysql.cj.jdbc.Driver
