server:
  port: 8091

spring:
  datasource:
    hikari:
      mysql1:
        jdbc-url: "jdbc:mysql://localhost:11001/test"
        username: "root"
        password: "P@ssw0rd"
        driver-class-name: com.mysql.cj.jdbc.Driver
      mysql2:
        jdbc-url: "jdbc:mysql://localhost:11002/test"
        username: "root"
        password: "P@ssw0rd"
        driver-class-name: com.mysql.cj.jdbc.Driver
