apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-env-test
spec:
  selector:
    matchLabels:
      app: configmap-env-test
  template:
    metadata:
      labels:
        app: configmap-env-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NGINX_PORT
          valueFrom:
            configMapKeyRef:
              name: nginx-config-env
              key: port
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-env
data:
  port: "8888"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-env
spec:
  selector:
    app: configmap-env-test
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
