apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test
spec:
  selector:
    matchLabels:
      app: secret-test
  template:
    metadata:
      labels:
        app: secret-test
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: MY_NAME
          valueFrom:
            secretKeyRef:
              name: my-info
              key: name
        volumeMounts:
          - name: my-publickey-volume
            mountPath: /etc/secrets
            readOnly: true
      volumes:
        - name: my-publickey-volume
          secret:
            secretName: my-publickey